
LEVELS = [
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H            S                 H",
        "H                              H",
        "H                              H",
        "H                    @         H",
        "H                              H",
        "H                              H",
        "H      O                       H",
        "H##############################H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H            S       @         H",
        "H                              H",
        "H                              H",
        "H      O                       H",
        "###########*****################",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H    S                         H",
        "H            O                 H",
        "H        ######      @         H",
        "H                              H",
        "H      ^                       H",
        "H    ######                    H",
        "H                              H",
        "H                              H",
        "H##############################H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H  S                           H",
        "H      @                       H",
        "H                              H",
        "H###############               H",
        "H                              H",
        "H                              H",
        "H  |       -----    |          H",
        "H                              H",
        "H                              H",
        "H     ^^^                      H",
        "H##########   *****************H",
        "H                              H",
        "H                              H",
        "H   |     ----               | H",
        "H                              H",
        "H                          O   H",
        "H                          #   H",
        "H******************************H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H      O                       H",
        "H      #                       H",
        "H                              H",
        "H  |----               |       H",
        "H                              H",
        "H  ******************     ###  H",
        "H                              H",
        "H                              H",
        "H            |        ---|     H",
        "H                   @          H",
        "H                              H",
        "H*******************##*********H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H            O                 H",
        "H      ########                H",
        "H                              H",
        "H   |           ------|        H",
        "H                              H",
        "H             |----        |   H",
        "H                              H",
        "H  |     -----    |            H",
        "H                              H",
        "H    @     |      -----  |     H",
        "H                              H",
        "################################",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                      O       H",
        "H                    #####     H",
        "H                              H",
        "H                ^             H",
        "H           ###############    H",
        "H         ##                   H",
        "H                              H",
        "H                              H",
        "H  ##***##                     H",
        "H        |  ----    |          H",
        "H                   ^    @     H",
        "H                 ####         H",
        "H   ^ ^ ^ ^ ^ ^         =      H",
        "H                              H",
        "H##############################H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             U                H",
        "H                              H",
        "H HHHHHHH  H    H  HHHHHH      H",
        "H    H     H    H  H           H",
        "H    H     HHHHHH  HHHHHH      H",
        "H    H     H    H  H           H",
        "H    H     H    H  HHHHHH      H",
        "H                              H",
        "H    HHHHHH  HH   H  HHH       H",
        "H    H       H H  H  H  HH     H",
        "H    HHHHHH  H  H H  H   H     H",
        "H    H       H   HH  H  HH     H",
        "H    HHHHHH  H    H  HHH       H",
        "H                              H",
        "H                    @         H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H##############################H",
    ],
]

LEVEL_SIGNS = [
    ["Move with the arrow keys"],
    ["Jump with space"],
    ["Jump on the slime"],
    ["Good luck!"],
    [],
    [],
    [],
    []
]
# Obviously not a good way to do this
# but I don't care
assert(len(LEVELS) == len(LEVEL_SIGNS))