
LEVELS = [
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             S                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                    @         H",
        "H                              H",
        "H                              H",
        "H      O                       H",
        "H##############################H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             S                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                    @         H",
        "H                              H",
        "H                              H",
        "H      O                       H",
        "###########*****################",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             S                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H            O                 H",
        "H        ######      @         H",
        "H                              H",
        "H      ^                       H",
        "H    ######                    H",
        "H                              H",
        "H                              H",
        "H##############################H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             S                H",
        "H                              H",
        "H      @                       H",
        "H                              H",
        "H###############               H",
        "H                              H",
        "H                              H",
        "H  |       -----    |          H",
        "H                              H",
        "H                              H",
        "H     ^^^                      H",
        "H##########   *****************H",
        "H                              H",
        "H                              H",
        "H   |     ----               | H",
        "H                              H",
        "H                          O   H",
        "H                          #   H",
        "H******************************H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             S                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H      O                       H",
        "H      #                       H",
        "H                              H",
        "H  |----               |       H",
        "H                              H",
        "H  ******************     ###  H",
        "H                              H",
        "H                              H",
        "H            |        ---|     H",
        "H                   @          H",
        "H                              H",
        "H*******************##*********H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             S                H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H                      O       H",
        "H                    #####     H",
        "H                              H",
        "H                ^             H",
        "H           ###############    H",
        "H         ##                   H",
        "H                              H",
        "H                              H",
        "H  ##***##                     H",
        "H        |  ----    |          H",
        "H                   ^    @     H",
        "H                 ####         H",
        "H   ^ ^ ^ ^ ^ ^         =      H",
        "H                              H",
        "H##############################H",
    ],
    [
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "H             S                H",
        "H                              H",
        "H HHHHHHH  H    H  HHHHHH      H",
        "H    H     H    H  H           H",
        "H    H     HHHHHH  HHHHHH      H",
        "H    H     H    H  H           H",
        "H    H     H    H  HHHHHH      H",
        "H                              H",
        "H    HHHHHH  HH   H  HHH       H",
        "H    H       H H  H  H  HH     H",
        "H    HHHHHH  H  H H  H   H     H",
        "H    H       H   HH  H  HH     H",
        "H    HHHHHH  H    H  HHH       H",
        "H                              H",
        "H                    @         H",
        "H                              H",
        "H                              H",
        "H                              H",
        "H##############################H",
    ],
]